# dev branch로 push 시에
name: Cypress Tests using Cypress Docker Image

on:
  push:
  pull_request:
    branches:
      - dev
  workflow_call:

jobs:
  # component-test:
  #   runs-on: ubuntu-22.04
  #   container:
  #     image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
  #     options: --user 1001
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Cypress run
  #       uses: cypress-io/github-action@v6
  #       with:
  #         build: npm run build
  #         start: npm start
  #         browser: chrome
  #         component: true
  #         working-directory: slid-todo

  e2e-test:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
      options: --user 1001
    steps:
      - name: Checkout
      uses: actions/checkout@v4

    # 의존성 캐싱 추가
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/slid-todo/.next/cache
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nextjs-

    # 환경변수 설정
    - name: Create env file
      run: |
        cd slid-todo
        echo "NEXT_PUBLIC_TEAM_ID=${{ secrets.TEAM_ID }}" > .env
        echo "NEXT_PUBLIC_TEST_EMAIL=${{ secrets.TEST_EMAIL }}" >> .env
        echo "NEXT_PUBLIC_TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}" >> .env

    - name: Cypress run
      uses: cypress-io/github-action@v6
      env:
        NODE_ENV: production
        TEAM_ID: ${{ secrets.TEAM_ID }}
        TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
        TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
      with:
        build: npm run build
        start: npm run start
        browser: chrome
        working-directory: slid-todo
