name: Cypress Test and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  cypress-test:
    uses: ./cypress-test.yml

  # deploy-production:
  #   name: Deploy to Vercel
  #   runs-on: ubuntu-latest
  #   needs: cypress-test
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install Vercel CLI
  #       run: npm install --global vercel@latest
  #     - name: Pull Vercel Environment Information
  #       run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
  #     - name: Build Project Artifacts
  #       run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
  #     - name: Deploy Project Artifacts to Vercel
  #       run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
