name: Cypress Test and Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  cypress-test:
    uses: ./.github/workflows/cypress-test.yml

  # deploy-production:
  # uses: ./vercel-deploy.yml
