name: Cypress Test and Deploy to Vercel

on:
  pull_request:
    branches:
      - main

jobs:
  cypress-test:
    uses: ./cypress-test.yml

  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: cypress-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod
