name: End-to-end tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm dependencies
        run: |
          cd slid-todo
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: slid-todo # 여기서 'slid-todo'를 지정
          start: npm start
