name: End-to-end tests

on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install npm dependencies
        run: |
          cd slid-todo
          npm install

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          working-directory: slid-todo
          start: npm start
