name: Cypress Tests using Cypress Docker Image

on:
  workflow_call:

jobs:
  deploy-production:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create env file
        run: |
          cd slid-todo
          echo "NEXT_PUBLIC_TEAM_ID=${{ secrets.TEAM_ID }}" > .env
          echo "NEXT_PUBLIC_TEST_EMAIL=${{ secrets.TEST_EMAIL }}" >> .env
          echo "NEXT_PUBLIC_TEST_PASSWORD=${{ secrets.TEST_PASSWORD }}" >> .env
          echo "NEXT_PUBLIC_API_URL=https://sp-slidtodo-api.vercel.app" >> .env

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          NEXT_PUBLIC_API_URL: https://sp-slidtodo-api.vercel.app

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          NEXT_PUBLIC_API_URL: https://sp-slidtodo-api.vercel.app

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          NEXT_PUBLIC_API_URL: https://sp-slidtodo-api.vercel.app
